#!/bin/bash
#
# preflight.sh — everything the demo needs BEFORE the first on-stage step.
#
# Runs the rehearsal preflight (R1–R5 of the demo outline) against lane-A:
#   R1  deploy a fresh univocity instance (generates the bootstrap ES256 key)
#   R2  operator-onboard the root genesis (mint onboard token + POST genesis)
#   R3  fetch + cache the public genesis for offline verification
#   R4  pre-delegate root sealing (so the first checkpoint lands in seconds)
#   R5  mint the self-referential root grant
#
# On success it writes ./demo.env with everything Step 1+ needs. Then:
#
#     source demo.env
#     # …and run Step 1 (see the printed commands at the end).
#
# Repeatable: each run deploys a FRESH forest (new bootstrap key + logId), so it
# never depends on prior state. Persona keys (David/Alice/Bob) are stable —
# generated once if absent. Requires: doppler auth (canopy/dev), the ./forestrie
# binary, node, jq, openssl, curl.
set -euo pipefail
cd "$(dirname "$0")"

step() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }

# --- secrets (preflight only; NOT written to demo.env) ---
export CANOPY_OPS_ADMIN_TOKEN=$(doppler secrets get CANOPY_OPS_ADMIN_TOKEN --project canopy --config dev --plain)
export DEPLOYER_KEY=$(doppler secrets get DEPLOY_KEY --project canopy --config dev --plain)

# --- lane-A config (public) ---
export FORESTRIE_BASE_URL="https://api-forest-2.forestrie.dev"
export RPC_URL="https://sepolia.base.org"
export CHAIN_ID=84532
export DELEGATION_COORDINATOR_URL="https://coordinator-a.forest-2.forestrie.dev"
export PINNED_REGISTRAR_KEY="z1YarLKXrsRe5egrwrFfbeYadd9lOqplKxbRuMGymHUOSY7YAfdOhhPWb3H72TrPMiMLw0CBMpDPXUGMEvbkOQ=="
export OWNER_ADDRESS="0xdA30dB778C4aAE42BfAE2e81d4b12dEb0725F98C"   # must match DEPLOYER_KEY
export ROBERT_PEM="./robert.es256.pem"
export DAVID_PEM="./david.es256.pem"
export ALICE_PEM="./alice.es256.pem"
export BOB_PEM="./bob.es256.pem"

# --- persona keys: stable across runs; generate only if missing ---
step "Persona keys (David / Alice / Bob)"
for pem in "$DAVID_PEM" "$ALICE_PEM" "$BOB_PEM"; do
  if [ -f "$pem" ]; then
    echo "  reuse $pem"
  else
    openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -outform PEM -out "$pem" >/dev/null 2>&1
    echo "  generated $pem"
  fi
done

# --- R1: deploy a fresh univocity instance (fresh bootstrap key) ---
step "R1 — deploy univocity + generate bootstrap key (on-chain, Base Sepolia)"
./forestrie deploy --bootstrap-alg es256 \
  --bootstrap-es256-generate --bootstrap-es256-pem-out "$ROBERT_PEM" \
  --owner-address "$OWNER_ADDRESS" --deployer-key "$DEPLOYER_KEY" \
  --rpc-url "$RPC_URL" --out deployment.json
export UNIVOCITY_ADDRESS=$(jq -r .imutableUnivocity deployment.json)
export ROBERT_LOG_ID=$(jq -r .genesisLogId deployment.json)
# deployment.json carries the txHash but not the block; resolve the deploy block
# from the receipt (portable — curl + jq only) so the Step-5 on-chain event
# query (fromBlock) works.
DEPLOY_TX=$(jq -r .txHash deployment.json)
DEPLOY_BLOCK_HEX=$(curl -fsS -X POST "$RPC_URL" -H 'Content-Type: application/json' \
  --data "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"eth_getTransactionReceipt\",\"params\":[\"$DEPLOY_TX\"]}" \
  | jq -r '.result.blockNumber // ""')
if [ -n "$DEPLOY_BLOCK_HEX" ] && [ "$DEPLOY_BLOCK_HEX" != "null" ]; then
  export DEPLOY_BLOCK=$(( DEPLOY_BLOCK_HEX ))
else
  export DEPLOY_BLOCK=""
fi
echo "  univocity=$UNIVOCITY_ADDRESS  logId=$ROBERT_LOG_ID  block=${DEPLOY_BLOCK:-<unresolved>}"

# --- R2: operator onboarding of the root genesis ---
step "R2 — onboard the root genesis (mint onboard token + POST genesis)"
node onboard-genesis.mjs

# --- R3: fetch + cache the public genesis (offline trust root forever after) ---
step "R3 — fetch + cache genesis.cbor"
curl -fsS -o genesis.cbor "$FORESTRIE_BASE_URL/api/forest/$ROBERT_LOG_ID/genesis"
echo "  wrote genesis.cbor ($(wc -c < genesis.cbor | tr -d ' ') bytes)"

# --- R4: pre-delegate root sealing (before the first write) ---
step "R4 — pre-delegate root sealing to the vouched standing sealer key"
./forestrie delegate --coordinator-url "$DELEGATION_COORDINATOR_URL" \
  --log-id "$ROBERT_LOG_ID" --sign-with "$ROBERT_PEM" \
  --pinned-registrar-key "$PINNED_REGISTRAR_KEY"

# --- R5: mint the self-referential root grant ---
step "R5 — mint the self-referential root grant"
./forestrie create-log --base-url "$FORESTRIE_BASE_URL" \
  --owner-log "$ROBERT_LOG_ID" --new-log "$ROBERT_LOG_ID" \
  --sign-with "$ROBERT_PEM" --self-referential --out-b64 root-grant.b64
export ROOT_GRANT_B64=$(cat root-grant.b64)

# --- write demo.env (secret-free; safe to leave on disk) ---
step "Writing demo.env"
cat > demo.env <<EOF
# Generated by preflight.sh — source this before the on-stage steps.
export FORESTRIE_BASE_URL="$FORESTRIE_BASE_URL"
export RPC_URL="$RPC_URL"
export CHAIN_ID=$CHAIN_ID
export DELEGATION_COORDINATOR_URL="$DELEGATION_COORDINATOR_URL"
export PINNED_REGISTRAR_KEY="$PINNED_REGISTRAR_KEY"
export ROBERT_PEM="$ROBERT_PEM"
export DAVID_PEM="$DAVID_PEM"
export ALICE_PEM="$ALICE_PEM"
export BOB_PEM="$BOB_PEM"
export UNIVOCITY_ADDRESS="$UNIVOCITY_ADDRESS"
export ROBERT_LOG_ID="$ROBERT_LOG_ID"
export DEPLOY_BLOCK="$DEPLOY_BLOCK"
export ROOT_GRANT_B64="$ROOT_GRANT_B64"
export GRANT_B64="$ROOT_GRANT_B64"
EOF
echo "  wrote demo.env"

cat <<'EOF'

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Preflight complete. The forest is deployed, onboarded, delegated, and granted.

Start the demo:

  source demo.env

Step 1 — register a signed statement and verify it offline:

  echo '{"claim":"hello scitt wg"}' > statement.json
  ./forestrie sign-statement --key "$ROBERT_PEM" --payload statement.json \
      --content-type application/json --out statement.cose
  REG=$(./forestrie register --base-url "$FORESTRIE_BASE_URL" \
      --log-id "$ROBERT_LOG_ID" --statement statement.cose \
      --grant-b64 "$ROOT_GRANT_B64" --out receipt.cbor 2>&1); echo "$REG"
  ENTRY_ID=$(echo "$REG" | grep -oE 'entries/[0-9a-f]{32}/receipt' | head -1 | grep -oE '[0-9a-f]{32}')
  ./forestrie verify --genesis genesis.cbor --receipt receipt.cbor \
      --payload statement.cose --entry-id "$ENTRY_ID"
